version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: "http://localhost:3000"
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  data:
